### ISSUE TITLE
Error: underlying network changed with version 8.2.0

### ISSUE THREAD

**Issue by ducndt** [Uniswap/web3-react#874]
Hi everyone, i follow the example of web3-react core and write the hook 

```
const useSwitchNetwork = () => {
  const [desiredChainId, setDesiredChainId] = useState(undefined);
  const { connector, chainId } = useWeb3React();
  const [error, setError] = useState(undefined);

  useEffect(() => {
    if (chainId && (!desiredChainId || desiredChainId === -1)) {
      setDesiredChainId(chainId);
    }
  }, [desiredChainId, chainId]);

  const switchNetwork = useCallback(
    async (desiredChainId) => {
      setDesiredChainId(desiredChainId);
      try {
        if (
          // If we're already connected to the desired chain, return
          desiredChainId === chainId ||
          // If they want to connect to the default chain and we're already connected, return
          (desiredChainId === -1 && chainId !== undefined)
        ) {
          setError(undefined);
          console.log('Go 35');
          return;
        }

        if (connector instanceof WalletConnectV2 || connector instanceof Network) {
          console.log('Go 40');
          await connector.activate(desiredChainId);
        } else {
          console.log('Go 43');
          await connector.activate(getAddChainParameters(desiredChainId));
        }

        setError(undefined);
      } catch (error) {
        console.log('Error switch: ', error);
        toast.error('Erorrrrrr: ', error);
        setError(error);
      }
    },
    [connector, chainId, setError],
  );

  return { switchNetwork, error };
};

```

When I try to switch chain, it throw the error 

`Error: underlying network changed (event="changed", network={"name":"matic","chainId":137,"ensAddress":null}, detectedNetwork`
But it still open the metamask and can change the network, but i don't know why it thow it. Any one can help me?
And when i use it with the scan of wallet connect (it can not switch chain, and it throw error underlying network immediately)

**Comment by arunkumar201** [comment]
I tested your hook in my demo and did not encounter the same error. Could you please provide more details on how to reproduce the error you are experiencing? It is possible that you are checking if the `connector` is an instance of `WalletConnectV2`, which can cause an error message of "Error switch: TypeError: Right-hand side of 'instanceof' is not callable...". However, I have implemented my switch logic using your custom hook and retrieved the current provider from localStorage. Based on this, I am able to switch and pass Network Params (for MetaMask) or chainId (for Wallet Connect and Coinbase). Here is the link to my demo: https://github.com/arunkumar201/Web3-Model/blob/useSwitchChainHook/src/hooks/useSwitchNetwork.tsx.

**Comment by ducndt** [comment]
Hello @arunkumar201 . I'm have this error when do the following: 

``` 
export default function useClaimTicket({ setStatus, chainId }) {
  const { switchNetwork } = useSwitchNetwork();
  const { account: signerAddress, provider: activeWeb3Provider } = useActiveWeb3React(chainId);

  const createClaimTicket = useCallback(
    async ({ redeemSignature }) => {
      try {
        
        await switchNetwork(chainId);

        const signer = activeWeb3Provider.getSigner();
        const contract = new ethers.Contract(tournamentAddress, CONTRACT_ABI, signer);

        const createClaimTransaction = await contract.claimTicket(
          redeemSignature?.id,
          redeemSignature?.signature,
          {
            gasLimit: GAS_LIMIT,
          },
        );

      } catch (error) {
        console.log('error: ', error);
        if (error.message.includes('user rejected transaction')) {
          toast.error('User reject transaction');
        } else {
          toast.error('Claim tickets failed. Please try again later');
        }
      }
    },
    [chainId, signerAddress],
  );

  return { createClaimTicket };
}
```

**Comment by ducndt** [comment]
I'm follow your example but maybe it's not the point

**Comment by arunkumar201** [comment]
Are you experiencing the issue only when using WalletConnect v2 and attempting to switch networks (chains) dynamically? Is that what you're trying to do?
If you are, then there's a bug. WalletConnect v2 does not support network (chain) switching from the browser (in your app) unless you have already manually added that chain to your respective mobile wallet. For more information, refer to: [https://github.com/Uniswap/web3-react/pull/853]

**Comment by ducndt** [comment]
In wallet connect v2 or metamask, it can switch to desired chain, but it still throw the error underlying and stop the process of interact with contract. So i think it's my fault, but i can't find where
